spring:
  datasource:
    url: jdbc:h2:mem:multibank;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console

multibank:
  bcr:
    base-url: ''
    api-key: ''
  bt:
    base-url: ''
    api-key: ''

logging:
  level:
    root: INFO
    org.springframework.web: INFO
